### ISSUE TITLE
Can not load phylo.. 

### ISSUE THREAD

**Issue by dylanHco** [thej022214/hisse#20] opened 2020-12-17 21:50 UTC
Hello,

I am having issues trying load phylogeny into hisse. 

 one.rate <- MiSSE(phy, f=1, turnover=turnover, eps=eps, sann=TRUE, sann.its=5000)

Error in if (sann == FALSE & starting.vals == NULL) {: argument is of length zero
Traceback:
1. MiSSE(phy, f = 1, turnover = turnover, eps = eps, sann = TRUE, 
 .     sann.its = 5000)

I see there is a pull request for this, but not sure what that means. 

Thanks for any advice,
Dylan Cohen

**Comment by thej022214** [comment] 2020-12-18 15:07
Hi Dylan:

Pull the version on CRAN. For some reason I didn't push onto GitHub before submitting version 1.9.10 onto CRAN. Weird. But the issue is fixed on here now too.

**Closed as completed by thej022214** 2020-12-18 15:07 UTC
